/**
 * Vendor configuration – pre-populated defaults for the quote calculator.
 *
 * All prices can be overridden by the salesperson at quote time.
 * usesBottles: false  →  Bottle section is hidden for that vendor.
 * multipleLocations: true → A second dropdown appears to pick the origin city.
 */

export const IBC_DESCRIPTIONS = [
  '275 Gal Rebottle IBC',
  '330 Gal Rebottle IBC',
  '135 Gal Rebottle IBC',
  '275 Gal Washouts IBC',
  '330 Gal Washouts IBC',
  '275 Gal New IBC',
  '330 Gal New IBC',
  '135 Gal New IBC',
  '55 Gal Drum',
  'Other',
]

export const US_STATES = [
  'AL','AK','AZ','AR','CA','CO','CT','DE','FL','GA',
  'HI','ID','IL','IN','IA','KS','KY','LA','ME','MD',
  'MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ',
  'NM','NY','NC','ND','OH','OK','OR','PA','RI','SC',
  'SD','TN','TX','UT','VT','VA','WA','WV','WI','WY',
]

export const VENDORS = [
  {
    id: 'rrg',
    name: 'RRG (Rural Recycling Grinding)',
    origin: { city: 'Stanwood', state: 'IA' },
    defaultBuyPrice: 60,
    usesBottles: true,
    defaultBottleCost: 58,
    defaultBottleFreightRate: 1100,
    defaultDescriptions: ['275 Gal Rebottle IBC', '330 Gal Rebottle IBC', '135 Gal Rebottle IBC', '275 Gal Washouts IBC'],
    defaultQtyByDescription: {
      '275 Gal Rebottle IBC': 60,
      '330 Gal Rebottle IBC': 78,
      '135 Gal Rebottle IBC': 120,
      '275 Gal Washouts IBC': 60,
    },
  },
  {
    id: 'sts',
    name: 'STS (Superior Tote Solutions) \u2013 Summitville',
    origin: { city: 'Summitville', state: 'IN' },
    defaultBuyPrice: 140,
    buyPriceByDescription: {
      '275 Gal Rebottle IBC':  140,
      '330 Gal Rebottle IBC':  160,
      '275 Gal Washouts IBC':  110,
    },
    usesBottles: false,
    defaultBottleCost: 0,
    defaultBottleFreightRate: 0,
    defaultDescriptions: ['275 Gal Rebottle IBC', '330 Gal Rebottle IBC', '135 Gal Rebottle IBC', '275 Gal Washouts IBC', '330 Gal Washouts IBC'],
    defaultQtyByDescription: {
      '275 Gal Rebottle IBC': 60,
      '330 Gal Rebottle IBC': 78,
      '135 Gal Rebottle IBC': 120,
      '275 Gal Washouts IBC': 60,
      '330 Gal Washouts IBC': 60,
    },
  },
  {
    id: 'sts-greenwood',
    name: 'STS (Superior Tote Solutions) \u2013 Greenwood',
    origin: { city: 'Greenwood', state: 'IN' },
    defaultBuyPrice: 140,
    buyPriceByDescription: {
      '275 Gal Rebottle IBC':  140,
      '330 Gal Rebottle IBC':  160,
      '275 Gal Washouts IBC':  110,
    },
    usesBottles: false,
    defaultBottleCost: 0,
    defaultBottleFreightRate: 0,
    defaultDescriptions: ['275 Gal Rebottle IBC', '330 Gal Rebottle IBC', '135 Gal Rebottle IBC', '275 Gal Washouts IBC', '330 Gal Washouts IBC'],
    defaultQtyByDescription: {
      '275 Gal Rebottle IBC': 60,
      '330 Gal Rebottle IBC': 78,
      '135 Gal Rebottle IBC': 120,
      '275 Gal Washouts IBC': 60,
      '330 Gal Washouts IBC': 60,
    },
  },
  {
    id: 'alliance-greenwood',
    name: 'Alliance Container \u2013 Greenwood',
    origin: { city: 'Greenwood', state: 'IN' },
    defaultBuyPrice: 0,
    usesBottles: true,
    defaultBottleCost: 58,
    defaultBottleFreightRate: 0,
    defaultDescriptions: ['275 Gal Rebottle IBC', '330 Gal Rebottle IBC'],
    defaultQtyByDescription: {
      '275 Gal Rebottle IBC': 90,
      '330 Gal Rebottle IBC': 78,
    },
  },
  {
    id: 'alliance-hillsboro',
    name: 'Alliance Container \u2013 Hillsboro',
    origin: { city: 'Hillsboro', state: 'TX' },
    defaultBuyPrice: 0,
    usesBottles: true,
    defaultBottleCost: 58.5,
    defaultBottleFreightRate: 0,
    defaultDescriptions: ['275 Gal Rebottle IBC', '330 Gal Rebottle IBC'],
    defaultQtyByDescription: {
      '275 Gal Rebottle IBC': 90,
      '330 Gal Rebottle IBC': 78,
    },
  },
  {
    id: 'eco-green',
    name: 'Eco Green',
    origin: { city: 'Houston', state: 'TX' },
    defaultBuyPrice: 0,
    usesBottles: true,
    defaultBottleCost: 0,
    defaultBottleFreightRate: 0,
    defaultDescriptions: ['275 Gal Rebottle IBC', '330 Gal Rebottle IBC'],
    defaultQtyByDescription: {
      '275 Gal Rebottle IBC': 90,
      '330 Gal Rebottle IBC': 78,
    },
  },
  {
    id: 'clean-environmental',
    name: 'Clean Environmental',
    origin: { city: 'St. Louis', state: 'MO' },
    defaultBuyPrice: 67.5,
    buyPriceByDescription: {
      '275 Gal Rebottle IBC': 67.5,
      '275 Gal Washouts IBC': 95,
    },
    usesBottles: true,
    defaultBottleCost: 55,
    defaultBottleFreightRate: 895,
    defaultDescriptions: ['275 Gal Rebottle IBC', '330 Gal Rebottle IBC', '135 Gal Rebottle IBC', '275 Gal Washouts IBC', '330 Gal Washouts IBC'],
    defaultQtyByDescription: {
      '275 Gal Rebottle IBC': 60,
      '330 Gal Rebottle IBC': 78,
      '135 Gal Rebottle IBC': 120,
      '275 Gal Washouts IBC': 60,
      '330 Gal Washouts IBC': 60,
    },
  },
  {
    id: 'core-ibcs',
    name: 'Core-IBCS',
    multipleLocations: true,
    locations: [
      { city: 'Houston',       state: 'TX' },
      { city: 'Nashua',        state: 'IA' },
      { city: 'Shreveport',    state: 'LA' },
      { city: 'South Holland', state: 'IL' },
      { city: 'Waterloo',      state: 'IA' },
      { city: 'Calhoun',       state: 'GA' },
    ],
    defaultBuyPrice: 155,
    buyPriceByDescription: {
      '275 Gal New IBC': 155,
      '330 Gal New IBC': 170,
      '135 Gal New IBC': 170,
    },
    usesBottles: false,
    defaultBottleCost: 0,
    defaultBottleFreightRate: 0,
    defaultDescriptions: ['275 Gal New IBC', '330 Gal New IBC', '135 Gal New IBC'],
    defaultQtyByDescription: {
      '275 Gal New IBC': 60,
      '330 Gal New IBC': 78,
      '135 Gal New IBC': 120,
    },
  },
  {
    id: 'united-container',
    name: 'United Container',
    origin: { city: 'Hillsboro', state: 'TX' },
    defaultBuyPrice: 65,
    buyPriceByDescription: {
      '275 Gal Rebottle IBC': 65,
      '330 Gal Rebottle IBC': 65,
      '275 Gal Washouts IBC': 85,
    },
    usesBottles: true,
    defaultBottleCost: 55,
    defaultBottleFreightRate: 0,
    defaultDescriptions: ['275 Gal Rebottle IBC', '330 Gal Rebottle IBC', '135 Gal Rebottle IBC'],
    defaultQtyByDescription: {
      '275 Gal Rebottle IBC': 60,
      '330 Gal Rebottle IBC': 78,
      '135 Gal Rebottle IBC': 120,
    },
  },
  {
    id: '5star',
    name: '5 Star Industrial Containers',
    origin: { city: 'Bristow', state: 'OK' },
    defaultBuyPrice: 65,
    buyPriceByDescription: {
      '275 Gal Rebottle IBC':  65,
      '330 Gal Rebottle IBC': 165,
      '275 Gal Washouts IBC':  80,
      '330 Gal Washouts IBC': 110,
    },
    usesBottles: true,
    defaultBottleCost: 55,
    defaultBottleFreightRate: 1025,
    defaultDescriptions: ['275 Gal Rebottle IBC', '330 Gal Rebottle IBC', '135 Gal Rebottle IBC', '275 Gal Washouts IBC', '330 Gal Washouts IBC'],
    defaultQtyByDescription: {
      '275 Gal Rebottle IBC': 60,
      '330 Gal Rebottle IBC': 78,
      '135 Gal Rebottle IBC': 120,
      '275 Gal Washouts IBC': 60,
      '330 Gal Washouts IBC': 60,
    },
  },
  {
    id: 'gpc',
    name: 'GPC (Great Plains \u2013 Garden City)',
    origin: { city: 'Garden City', state: 'KS' },
    defaultBuyPrice: 65,
    buyPriceByDescription: {
      '275 Gal Rebottle IBC': 65,
      '275 Gal Washouts IBC': 90,
    },
    usesBottles: true,
    defaultBottleCost: 55,
    defaultBottleFreightRate: 1335,
    defaultDescriptions: ['275 Gal Rebottle IBC', '330 Gal Rebottle IBC', '135 Gal Rebottle IBC', '275 Gal Washouts IBC', '330 Gal Washouts IBC'],
    defaultQtyByDescription: {
      '275 Gal Rebottle IBC': 60,
      '330 Gal Rebottle IBC': 78,
      '135 Gal Rebottle IBC': 120,
      '275 Gal Washouts IBC': 60,
      '330 Gal Washouts IBC': 60,
    },
  },
  {
    id: 'sec',
    name: 'SEC (SouthEast Container)',
    origin: { city: 'Cleveland', state: 'MS' },
    defaultBuyPrice: 75,
    buyPriceByDescription: {
      '275 Gal Rebottle IBC':  75,
      '330 Gal Rebottle IBC':  88,
      '275 Gal Washouts IBC':  85,
      '330 Gal Washouts IBC': 105,
    },
    usesBottles: true,
    defaultBottleCost: 55,
    defaultBottleFreightRate: 995,
    defaultDescriptions: ['275 Gal Rebottle IBC', '330 Gal Rebottle IBC', '135 Gal Rebottle IBC', '275 Gal Washouts IBC', '330 Gal Washouts IBC'],
    defaultQtyByDescription: {
      '275 Gal Rebottle IBC': 60,
      '330 Gal Rebottle IBC': 78,
      '135 Gal Rebottle IBC': 120,
      '275 Gal Washouts IBC': 60,
      '330 Gal Washouts IBC': 60,
    },
  },
  {
    id: 'ted-levine',
    name: 'Ted Levine Drum Co',
    origin: { city: 'South El Monte', state: 'CA' },
    defaultBuyPrice: 160,
    buyPriceByDescription: {
      '275 Gal Rebottle IBC': 160,
      '330 Gal Rebottle IBC': 175,
      '275 Gal Washouts IBC': 105,
    },
    usesBottles: false,
    defaultBottleCost: 0,
    defaultBottleFreightRate: 0,
    defaultDescriptions: ['275 Gal Rebottle IBC', '330 Gal Rebottle IBC', '135 Gal Rebottle IBC'],
    defaultQtyByDescription: {
      '275 Gal Rebottle IBC': 60,
      '330 Gal Rebottle IBC': 78,
      '135 Gal Rebottle IBC': 120,
    },
  },
  {
    id: 'ttw',
    name: 'TTW (Texas Tote Works)',
    origin: { city: 'Odessa', state: 'TX' },
    defaultBuyPrice: 85,
    buyPriceByDescription: {
      '275 Gal Washouts IBC':  85,
      '330 Gal Washouts IBC': 110,
    },
    usesBottles: false,
    defaultBottleCost: 0,
    defaultBottleFreightRate: 0,
    defaultDescriptions: ['275 Gal Rebottle IBC', '330 Gal Rebottle IBC', '135 Gal Rebottle IBC', '275 Gal Washouts IBC', '330 Gal Washouts IBC'],
    defaultQtyByDescription: {
      '275 Gal Rebottle IBC': 60,
      '330 Gal Rebottle IBC': 78,
      '135 Gal Rebottle IBC': 120,
      '275 Gal Washouts IBC': 60,
      '330 Gal Washouts IBC': 60,
    },
  },
  {
    id: 'centurion',
    name: 'Centurion',
    multipleLocations: true,
    locations: [
      { city: 'Lewisburg', state: 'TN' },
      { city: 'Memphis',   state: 'TN' },
    ],
    defaultBuyPrice: 0,
    usesBottles: true,
    defaultBottleCost: 0,
    defaultBottleFreightRate: 0,
    defaultDescriptions: ['275 Gal Rebottle IBC', '330 Gal Rebottle IBC', '135 Gal Rebottle IBC', '275 Gal Washouts IBC', '330 Gal Washouts IBC'],
    defaultQtyByDescription: {
      '275 Gal Rebottle IBC': 60,
      '330 Gal Rebottle IBC': 78,
      '135 Gal Rebottle IBC': 120,
      '275 Gal Washouts IBC': 60,
      '330 Gal Washouts IBC': 60,
    },
  },
]

/** Customer list sourced from Tracking MPH Deals – Lists sheet */
export const CUSTOMERS = [
  '5 Star Industrial Containers - Bristow, OK',
  'A1 Rotomold',
  'Acid Products Company',
  'Achieved Investments',
  'Adjuvants',
  'Ag Ingenuity',
  'Ag Spray Equipment',
  'Agpack',
  'Agri Partners',
  'AgTank Solutions',
  'Agtegra Cooperative',
  'Alliance Container - Greenwood, IN',
  'Alliance Container - Hillsboro, TX',
  'Apex Drum Company',
  'Arts Milling Service',
  'AU Solutions',
  'Axel Americas',
  'Axel Royal',
  'Barton Solvents',
  'Beck Flavors',
  'Berlin Packaging',
  'Brandt Consolidated',
  'Caleb Chemical',
  'Catalynt Solutions',
  'CDF Corporation',
  'Celta Chemical',
  'Centurion Container',
  'Chemline',
  'Chemorse',
  'Chemtrade Refinery Services',
  'CHS',
  'CL Smith',
  'Clean Environmental - St. Louis, MO',
  'Coalition',
  'Coastal Bend Containers',
  'Coastal Container Services',
  'Colorbiotics',
  'Container Compliance',
  'Container Connectionz',
  'Container Recycling',
  'Container Technology',
  'Containers Unlimited',
  'Cotey Chemical Corporation',
  'Countryside Feed',
  'Crosslink of New Mexico',
  'Crown Packaging',
  'Delaval Manufacturing',
  'Diamond Vogel',
  'Drexel Chemical Company',
  'Dynachem',
  'Earth Science Laboratories',
  'Echo Global Logistics',
  'ECO Green',
  'ECO-Pak',
  'EGE Products',
  'ENGY Southwest Container Products',
  'Enviro Containers and Recycling',
  'Enviro Science Technologies',
  'Equity Exchange',
  'Essential Industries',
  'Eureka Chemical Labs',
  'FarmChem',
  'Floratine Products Group',
  'Florida Coastal Colors',
  'Frontier Logistical Services',
  'Fuller Industries',
  'Gates Engineered Lubricants',
  'Genesis Custom Chemical Blending',
  'Geo Chemicals',
  'GPC (Great Plains Containers) - Garden City, KS',
  'Greenpoint AG Holdings',
  'Guadalupe Cervantes',
  'Hafa Industries',
  'Hampel Oil Distributors',
  'Hartland Lubricants & Chemicals',
  'HB Fuller',
  'Helena Agri-Enterprises',
  'HGS BioScience',
  'Holganix',
  'IBC Tote Recycling',
  'Industrial Chemicals',
  'Inland Star /CO LPI',
  'Integrity Bio-Chem',
  'Interstate Ag Containers',
  'IOU (Industrial Oils Unlimited)',
  'Josh Berna',
  'KCI Chemicals',
  'Kemin Industries',
  'Kodiak AI',
  'Koppers Performance Chemicals',
  'Ksolv',
  'Lamberti USA',
  'Land O Lakes',
  'Landus Ag',
  'Lionel\'s Drums Pallets & Totes',
  'Loveland Products',
  'M-Con Solutions',
  'Marks Barrel Co',
  'Master Builders',
  'MBCC Group',
  'McKenzie Begin and Assoc.',
  'Merrel Transport',
  'Microsource',
  'Mitchell Container',
  'MPH STK to 5 Star',
  'MPH STK to Alliance-Greenwood IN',
  'MPH STK to Alliance-Hillsboro',
  'MPH STK to Clean Environmental',
  'MPH STK to Great Plains \u2013 KS',
  'MPH STK to RRG',
  'MPH STK to SEC',
  'MPH STK to STS-Greenwood IN',
  'MPH STK to Ted Levine Drum Co',
  'MPH STK to United Container',
  'MPH United',
  'Neighbor Distribution',
  'Nielsen-Massey\'s Vanillas',
  'Novus Ag',
  'Nox-Crete',
  'Nufarm Americas Inc. - Cascio Warehouse',
  'Nutrien Ag Solutions',
  'Nutrien Ag Solutions - Alberta, MN',
  'Nutrien Ag Solutions - Alexis, IL',
  'Nutrien Ag Solutions - Arlington, NE',
  'Nutrien Ag Solutions - Ashland, NE',
  'Nutrien Ag Solutions - Atalissa, IA',
  'Nutrien Ag Solutions - Atchison, KS',
  'Nutrien Ag Solutions - Atlanta, IL',
  'Nutrien Ag Solutions - Attica, OH',
  'Nutrien Ag Solutions - Atwood, KS',
  'Nutrien Ag Solutions - Beloit, KS',
  'Nutrien Ag Solutions - Big Lake, MN',
  'Nutrien Ag Solutions - Biggsville, IL',
  'Nutrien Ag Solutions - Billings, MT',
  'Nutrien Ag Solutions - Bird City, KS',
  'Nutrien Ag Solutions - Bismark, ND',
  'Nutrien Ag Solutions - Blue Earth, MN',
  'Nutrien Ag Solutions - Brookings, SD',
  'Nutrien Ag Solutions - Brown City, MI',
  'Nutrien Ag Solutions - Burlington, CO',
  'Nutrien Ag Solutions - Clay Center, KS',
  'Nutrien Ag Solutions - Colby, KS',
  'Nutrien Ag Solutions - Concordia, KS',
  'Nutrien Ag Solutions - Corning, IA',
  'Nutrien Ag Solutions - Dallas, TX',
  'Nutrien Ag Solutions - Davenport, NE',
  'Nutrien Ag Solutions - Dixon, IL',
  'Nutrien Ag Solutions - Dumas, TX',
  'Nutrien Ag Solutions - Edna, TX',
  'Nutrien Ag Solutions - Fairbury, NE',
  'Nutrien Ag Solutions - Fairmont, MN',
  'Nutrien Ag Solutions - Galesburg, IL',
  'Nutrien Ag Solutions - Garden City, KS',
  'Nutrien Ag Solutions - Goodland, KS',
  'Nutrien Ag Solutions - Hamler, OH',
  'Nutrien Ag Solutions - Henderson, MI',
  'Nutrien Ag Solutions - Hoxie, KS',
  'Nutrien Ag Solutions - Imperial, NE',
  'Nutrien Ag Solutions - Kingstree, SC',
  'Nutrien Ag Solutions - LaCrosse, KS',
  'Nutrien Ag Solutions - Lamar, NE',
  'Nutrien Ag Solutions - Lincoln, IL',
  'Nutrien Ag Solutions - Loveland, CO',
  'Nutrien Ag Solutions - Lu Verne, IA',
  'Nutrien Ag Solutions - Mapleton, ND',
  'Nutrien Ag Solutions - McCook, NE',
  'Nutrien Ag Solutions - Mendon, MI',
  'Nutrien Ag Solutions - Mineral Point, WI',
  'Nutrien Ag Solutions - Moody, TX',
  'Nutrien Ag Solutions - Mt Sterling, OH',
  'Nutrien Ag Solutions - Munger, MI',
  'Nutrien Ag Solutions - Northville, SD',
  'Nutrien Ag Solutions - Oakley, KS',
  'Nutrien Ag Solutions - Oberlin, KS',
  'Nutrien Ag Solutions - Owendale, MI',
  'Nutrien Ag Solutions - Owensboro, KY',
  'Nutrien Ag Solutions - Pantego, NC',
  'Nutrien Ag Solutions - Polk, OH',
  'Nutrien Ag Solutions - Rayville, LA',
  'Nutrien Ag Solutions - Reading, MI',
  'Nutrien Ag Solutions - Reinbeck, IA',
  'Nutrien Ag Solutions - Salem, KY',
  'Nutrien Ag Solutions - Selma, IN',
  'Nutrien Ag Solutions - Senath, MO',
  'Nutrien Ag Solutions - Seneca, KS',
  'Nutrien Ag Solutions - Shelby, KY',
  'Nutrien Ag Solutions - Smith Center, KS',
  'Nutrien Ag Solutions - Sunfield, MI',
  'Nutrien Ag Solutions - Taft, TX',
  'Nutrien Ag Solutions - Tarboro, NC',
  'Nutrien Ag Solutions - Taylor, TX',
  'Nutrien Ag Solutions - Tipton, IN',
  'Nutrien Ag Solutions - Upper Sandusky, OH',
  'Nutrien Ag Solutions - WaKeeney, KS',
  'Nutrien Ag Solutions - Wall Lake, IA',
  'Nutrien Ag Solutions - West Liberty, IA',
  'Nutrien Ag Solutions - Williston, ND',
  'Nutrien Ag Solutions - Winthrop, IA',
  'Oasis Chemicals',
  'Obsidian Chemical Solutions',
  'Pencco',
  'Phoenix Flooring',
  'Pinnacle Resources',
  'Pipeline Packaging',
  'Plant Nuco',
  'Plasmine Technology',
  'Platte Chemical',
  'Polycon Industries',
  'Prairie Packaging',
  'Precision Dynamics',
  'Premier Container',
  'Prescription Ag',
  'Presley Enterprises',
  'Protank',
  'Quanta Containers',
  'Ralco Nutrition',
  'Research Solutions',
  'Responsible Container',
  'Richard E. Colgin I LTD',
  'Roberts Sinto Corporation',
  'Rosen\'s',
  'Rovensa Next',
  'RRG (Rural Recycling Grinding) - Stanwood, IA',
  'SEATEX',
  'SEC (SouthEast Container) - Cleveland, MS',
  'Sigma Recycling',
  'Simplot Grower Solutions',
  'Sipcam',
  'Skyland Grain',
  'Southern Container',
  'SpecChem',
  'Specialty Adhesives & Coatings',
  'Specialty Ag Formulations',
  'Spectrum Adhesives',
  'SRS (Sound Resource Solutions)',
  'Statera Manufacturing LLC',
  'Steve Strba Consulting',
  'STS (Superior Tote Solution) - Greenwood, IN',
  'STS (Superior Tote Solution) - Summitville, IN',
  'Sweet Life Services',
  'TBK One',
  'Team Laboratory Chemical',
  'The Andersons',
  'The Cary Company',
  'The Way',
  'TLD (Ted Levine Drum Co) - South El Monte, CA',
  'Transchemical',
  'Tri Rinse',
  'Tri Star Chemical',
  'TTW (Texas Tote Works) - Odessa, TX',
  'UCG (United Container Group)',
  'Urnex Brands',
  'Valent Biosciences Corp C/O A-Z Drying',
  'Vantage Specialties',
  'VLS Recovery',
  'Water Tech',
  'Weiman Products c/o Somers Offsite Storage',
  'West Drum & Container',
  'Wilbur-Ellis',
  'Winfield United',
]
